// linux: g++ -O2 -std=c++17 gen_obf.cpp -o gen_simple
// msvc:  cl gen_obf.cpp
// macOS: clang++ ../src/gen_obf.cpp -o gen_obf
// Usage: ./gen_obf "YOUR_API_KEY"
// Emits an obfuscated Google maps API key in obfuscated format to be pasted
// in RGGoogleMap.cpp

#include <iostream>
#include <vector>
using namespace std;

int main(int argc, char** argv) {
    if (argc < 2) {
        cerr << "Usage: " << argv[0] << " \"API_KEY\"\n";
        return 1;
    }
    string key = argv[1];

    vector<int> v;
    v.reserve(key.size());
    for (unsigned char c : key) v.push_back(int(c) * 42);

    cout << "// Generated by gen_obf.cpp - paste into your source (release build)\n";
    cout << "static const unsigned short obf_key[] = { ";
    for (int i = (int)v.size()-1; i >= 0; --i) {
        cout << v[i];
        if (i != 0) cout << ", ";
    }
    cout << " };\n";
    cout << "static const size_t obf_key_len = sizeof(obf_key)/sizeof(obf_key[0]);\n";
    return 0;
}
